<?php
/******************************************************************************
* Class for neocosur.evaluacion_neurodesarrolloDAO
*******************************************************************************/

class evaluacion_neurodesarrolloDAO
{
	private $conexionDao;
	private $id;	
	function __construct($cone)
	{
		$this->conexionDao = $cone;			
	}

	public function setId($id='')
	{
		$this->id = $id;
		return true;
	}

	public function getId()
	{
		return $this->id;
	}
	
	
	public function guarda($evaluacion_neurodesarrollo)
	{
		$query ="INSERT INTO `evaluacion_neurodesarrollo` 
		(
			`ID_CONTROL`, 
			`HIC_40_SEMANA`, 
			`ID_HIC_40_GRADO`,
			`LPV_40SEMANAS`, 
			`ROP_40_SEMANAS`,
			`ROP_40_SEMANAS_GRADO`,
			`BERA_40SEMANAS`,
			`NEUROLOGICA_2_VISION`,
			`NEUROLOGICA_2_VISION_CEGUERA`, 
			`NEUROLOGICA_2_VISION_ESTRABISMO`, 
			`NEUROLOGICA_2_VISION_REFRACCION`, 
			`NEUROLOGICA_2_AUDICION`, 
			`NEUROLOGICA_2_AUDICION_NO`, 
			`NEUROLOGICA_2_MOTORA`, 
			`NEUROLOGICA_2_PARALISIS`, 
			`NEUROLOGICA_2_PARALISIS_SI`, 
			`NEUROLOGICA_2_COGNITIVA`, 
			`NEUROLOGICA_2_OTROS`, 
			`NEUROLOGICA_2_OTROS_CONVULSIVO`, 
			`NEUROLOGICA_2_OTROS_HIDROCEFALIA`, 
			`PSICOMOTOR_2_EXAMEN`, 
			`PSICOMOTOR_2_EX_HIPO`, 
			`PSICOMOTOR_2_EX_HIPER`, 
			`PSICOMOTOR_2_EX_FOCA`, 
			`PSICOMOTOR_2_EXA_HEMI`, 
			`PSICOMOTOR_2_AUDITIVA_SEN`, 
			`PSICOMOTOR_2_AUDITIVA_SEN_HIPO`, 
			`PSICOMOTOR_2_AUDITIVA_SEN_VISUAL`, 
			`PSICOMOTOR_2_AUDITIVA_SEN_CIRUGIA`, 
			`PSICOMOTOR_2_AUDITIVA_SEN_CIRUGIA_DESCI`, 
			`PSICOMOTOR_2_AUDITIVA_RETRA_LENGUA`, 
			`PSICOMOTOR_2_AUDITIVA_RETRA_LENGUA_SI`, 
			`PSICOMOTOR_2_AUDITIVA_OTRO_CEFALIA`, 
			`PSICOMOTOR_2_AUDITIVA_OTRO_SINDRO`, 
			`PSICOMOTOR_2_AUDITIVA_OTRO_ALTERA`, 
			`PSICOMOTOR_2_AUDITIVA_NEURO`, 
			`PSICOMOTOR_A2ANIOS_MESES`, 
			`PSICOMOTOR_A2ANIOS_EEDP_CUAL`, 
			`PSICOMOTOR_A2ANIOS_EEDP_FECHA`, 
			`PSICOMOTOR_A2ANIOS_EEDP_ANIOS`, 
			`PSICOMOTOR_A2ANIOS_EEDP_MESES`, 
			`PSICOMOTOR_A2ANIOS_EEDP_PUNTAJE`, 
			`PSICOMOTOR_A2ANIOS_EEDP_NORMAL`, 
			`PSICOMOTOR_A2ANIOS_EEDP_OBSERVACION`, 
			`PSICOMOTOR_A2ANIOS_EAIS_CUAL`, 
			`PSICOMOTOR_A2ANIOS_EAIS_FECHA`, 
			`PSICOMOTOR_A2ANIOS_EAIS_ANIOS`, 
			`PSICOMOTOR_A2ANIOS_EAIS_MESES`, 
			`PSICOMOTOR_A2ANIOS_EAIS_PUNTAJE`, 
			`PSICOMOTOR_A2ANIOS_EAIS_NORMAL`, 
			`PSICOMOTOR_A2ANIOS_EAIS_OBSERVACION`, 
			`PSICOMOTOR_A2ANIOS_CAT_CUAL`, 
			`PSICOMOTOR_A2ANIOS_CAT_FECHA`, 
			`PSICOMOTOR_A2ANIOS_CAT_ANIOS`, 
			`PSICOMOTOR_A2ANIOS_CAT_MESES`, 
			`PSICOMOTOR_A2ANIOS_CAT_PUNTAJE`, 
			`PSICOMOTOR_A2ANIOS_CAT_NORMAL`, 
			`PSICOMOTOR_A2ANIOS_CAT_OBSERVACION`, 
			`PSICOMOTOR_A2ANIOS_ASQ_CUAL`, 
			`PSICOMOTOR_A2ANIOS_ASQ_FECHA`, 
			`PSICOMOTOR_A2ANIOS_ASQ_ANIOS`, 
			`PSICOMOTOR_A2ANIOS_ASQ_MESES`, 
			`PSICOMOTOR_A2ANIOS_ASQ_PUNTAJE`, 
			`PSICOMOTOR_A2ANIOS_ASQ_NORMAL`, 
			`PSICOMOTOR_A2ANIOS_ASQ_OBSERVACION`, 
			`PSICOMOTOR_2A7ANIOS_TEPSI`, 
			`PSICOMOTOR_2A7ANIOS_TEP_NORMAL`, 
			`PSICOMOTOR_2A7ANIOS_TEP_FECHA`, 
			`PSICOMOTOR_2A7ANIOS_TEP_ANIOS`, 
			`PSICOMOTOR_2A7ANIOS_TEP_MESES`, 
			`PSICOMOTOR_2A7ANIOS_TEP_PUNTAJE`, 
			`PSICOMOTOR_2A7ANIOS_BAYLE`, 
			`PSICOMOTOR_2A7ANIOS_BAYLE_VERSION`, 
			`PSICOMOTOR_2A7ANIOS_BAYLE_VER_FECHA`, 
			`PSICOMOTOR_2A7ANIOS_BAYLE_VER_ANIOS`, 
			`PSICOMOTOR_2A7ANIOS_BAYLE_VER_MESES`, 
			`PSICOMOTOR_2A7ANIOS_BAYLE_VER_MENTAL`, 
			`PSICOMOTOR_2A7ANIOS_BAYLE_VER_MOTARA`, 
			`PSICOMOTOR_2A7ANIOS_BAYLE_VER_CONDUCTA`, 
			`PSICOMOTOR_2A7ANIOS_BAYLE_VER_NORMAL`, 
			`PSICOMOTOR_2A7ANIOS_BAYLE_VER_FECHA_3`, 
			`PSICOMOTOR_2A7ANIOS_BAYLE_VER_ANIOS_3`, 
			`PSICOMOTOR_2A7ANIOS_BAYLE_VER_MESES_3`, 
			`PSICOMOTOR_2A7ANIOS_BAYLE_VER_MOTARA_3`, 
			`PSICOMOTOR_2A7ANIOS_BAYLE_VER_COGNI_3`, 
			`PSICOMOTOR_2A7ANIOS_BAYLE_VER_LENG_3`, 
			`PSICOMOTOR_2A7ANIOS_BAYLE_VER_SOCIO_3`, 
			`PSICOMOTOR_2A7ANIOS_BAYLE_VER_COMPOR_3`, 
			`PSICOMOTOR_2A7ANIOS_BAYLE_VER_NORMAL_3`, 
			`PSICOMOTOR_A3ANIOS_RET_LENG`, 
			`PSICOMOTOR_A3ANIOS_RET_LENG_TIPO`, 
			`PSICOMOTOR_A3ANIOS_RET_LENG_REHAB`, 
			`PSICOMOTOR_3ANIOS_RET_EXPRESIVO`, 
			`PSICOMOTOR_3ANIOS_RET_EXPRESIVO_REHAB`, 
			`PSICOMOTOR_2A4ANIOS_COEFICIENTE`, 
			`PSICOMOTOR_2A4ANIOS_COE_FECHA_1`, 
			`PSICOMOTOR_2A4ANIOS_COE_ANIOS_1`, 
			`PSICOMOTOR_2A4ANIOS_COE_MESES_1`, 
			`PSICOMOTOR_2A4ANIOS_COE_VERB_1`, 
			`PSICOMOTOR_2A4ANIOS_COE_MANIPU_1`, 
			`PSICOMOTOR_2A4ANIOS_COE_TOTAL_1`, 
			`PSICOMOTOR_2A4ANIOS_COE_FECHA_2`, 
			`PSICOMOTOR_2A4ANIOS_COE_ANIOS_2`, 
			`PSICOMOTOR_2A4ANIOS_COE_MESES_2`, 
			`PSICOMOTOR_2A4ANIOS_COE_VERB_2`, 
			`PSICOMOTOR_2A4ANIOS_COE_MANIPU_2`, 
			`PSICOMOTOR_2A4ANIOS_COE_PROCESA_2`, 
			`PSICOMOTOR_2A4ANIOS_COE_LENGUAJE_2`, 
			`PSICOMOTOR_2A4ANIOS_OTRO_MSCA`, 
			`PSICOMOTOR_2A4ANIOS_OTRO_SCQ`, 
			`PSICOMOTOR_2A4ANIOS_OTRO_MCHAT`, 
			`PSICOMOTOR_2A4ANIOS_OTRO_VABS`, 
			`PSICOMOTOR_2A4ANIOS_OTRO_GMFCS`, 
			`PSICOMOTOR_2A4ANIOS_OTRO_OBSERV`, 
			`NEURODESAROLLO_2ANIOS_MOTORA`, 
			`NEURODESAROLLO_2ANIOS_MOTORA_NIVEL`, 
			`NEURODESAROLLO_2ANIOS_PARALISIS`, 
			`NEURODESAROLLO_2ANIOS_PARALISIS_CUAL`, 
			`NEURODESAROLLO_2ANIOS_OTROS_TRANSTORNOS`, 
			`NEURODESAROLLO_2ANIOS_OTROS_LENGUAJE`, 
			`NEURODESAROLLO_2ANIOS_OTROS_APRENDIZAJE`
		) 
		VALUES ( ?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?
			);";
		
		$this->conexionDao->Abrir();
		$sentencia = $this->conexionDao->prepare($query);		
		$sentencia->bind_param("sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss",
			$evaluacion_neurodesarrollo->ID_CONTROL,
			$evaluacion_neurodesarrollo->HIC_40_SEMANA,
			$evaluacion_neurodesarrollo->ID_HIC_40_GRADO,
			$evaluacion_neurodesarrollo->LPV_40SEMANAS,
			$evaluacion_neurodesarrollo->ROP_40_SEMANAS,
			$evaluacion_neurodesarrollo->ROP_40_SEMANAS_GRADO,
			$evaluacion_neurodesarrollo->BERA_40SEMANAS,
			$evaluacion_neurodesarrollo->NEUROLOGICA_2_VISION,
			$evaluacion_neurodesarrollo->NEUROLOGICA_2_VISION_CEGUERA,
			$evaluacion_neurodesarrollo->NEUROLOGICA_2_VISION_ESTRABISMO,
			$evaluacion_neurodesarrollo->NEUROLOGICA_2_VISION_REFRACCION,
			$evaluacion_neurodesarrollo->NEUROLOGICA_2_AUDICION,
			$evaluacion_neurodesarrollo->NEUROLOGICA_2_AUDICION_NO	,
			$evaluacion_neurodesarrollo->NEUROLOGICA_2_MOTORA,
			$evaluacion_neurodesarrollo->NEUROLOGICA_2_PARALISIS	,
			$evaluacion_neurodesarrollo->NEUROLOGICA_2_PARALISIS_SI	,
			$evaluacion_neurodesarrollo->NEUROLOGICA_2_COGNITIVA	,
			$evaluacion_neurodesarrollo->NEUROLOGICA_2_OTROS,
			$evaluacion_neurodesarrollo->NEUROLOGICA_2_OTROS_CONVULSIVO,
			$evaluacion_neurodesarrollo->NEUROLOGICA_2_OTROS_HIDROCEFALIA,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2_EXAMEN,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2_EX_HIPO,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2_EX_HIPER,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2_EX_FOCA,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2_EXA_HEMI,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2_AUDITIVA_SEN	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2_AUDITIVA_SEN_HIPO,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2_AUDITIVA_SEN_VISUAL,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2_AUDITIVA_SEN_CIRUGIA,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2_AUDITIVA_SEN_CIRUGIA_DESCI,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2_AUDITIVA_RETRA_LENGUA,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2_AUDITIVA_RETRA_LENGUA_SI	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2_AUDITIVA_OTRO_CEFALIA,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2_AUDITIVA_OTRO_SINDRO,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2_AUDITIVA_OTRO_ALTERA,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2_AUDITIVA_NEURO,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_MESES	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_EEDP_CUAL,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_EEDP_FECHA,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_EEDP_ANIOS,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_EEDP_MESES,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_EEDP_PUNTAJE,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_EEDP_NORMAL,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_EEDP_OBSERVACION	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_EAIS_CUAL,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_EAIS_FECHA,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_EAIS_ANIOS,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_EAIS_MESES,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_EAIS_PUNTAJE,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_EAIS_NORMAL,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_EAIS_OBSERVACION	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_CAT_CUAL,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_CAT_FECHA,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_CAT_ANIOS,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_CAT_MESES,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_CAT_PUNTAJE,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_CAT_NORMAL,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_CAT_OBSERVACION,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_ASQ_CUAL,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_ASQ_FECHA,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_ASQ_ANIOS,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_ASQ_MESES,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_ASQ_PUNTAJE,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_ASQ_NORMAL,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_ASQ_OBSERVACION,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_TEPSI	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_TEP_NORMAL,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_TEP_FECHA,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_TEP_ANIOS,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_TEP_MESES,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_TEP_PUNTAJE,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_BAYLE	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_BAYLE_VERSION,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_BAYLE_VER_FECHA	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_BAYLE_VER_ANIOS	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_BAYLE_VER_MESES	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_BAYLE_VER_MENTAL	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_BAYLE_VER_MOTARA	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_BAYLE_VER_CONDUCTA	,			
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_BAYLE_VER_NORMAL	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_BAYLE_VER_FECHA_3	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_BAYLE_VER_ANIOS_3	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_BAYLE_VER_MESES_3	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_BAYLE_VER_MOTARA_3	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_BAYLE_VER_COGNI_3	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_BAYLE_VER_LENG_3	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_BAYLE_VER_SOCIO_3	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_BAYLE_VER_COMPOR_3	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_BAYLE_VER_NORMAL_3	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A3ANIOS_RET_LENG,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A3ANIOS_RET_LENG_TIPO,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A3ANIOS_RET_LENG_REHAB,
			$evaluacion_neurodesarrollo->PSICOMOTOR_3ANIOS_RET_EXPRESIVO,
			$evaluacion_neurodesarrollo->PSICOMOTOR_3ANIOS_RET_EXPRESIVO_REHAB	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A4ANIOS_COEFICIENTE,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A4ANIOS_COE_FECHA_1,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A4ANIOS_COE_ANIOS_1,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A4ANIOS_COE_MESES_1,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A4ANIOS_COE_VERB_1,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A4ANIOS_COE_MANIPU_1,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A4ANIOS_COE_TOTAL_1,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A4ANIOS_COE_FECHA_2,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A4ANIOS_COE_ANIOS_2,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A4ANIOS_COE_MESES_2,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A4ANIOS_COE_VERB_2,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A4ANIOS_COE_MANIPU_2,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A4ANIOS_COE_PROCESA_2,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A4ANIOS_COE_LENGUAJE_2,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A4ANIOS_OTRO_MSCA,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A4ANIOS_OTRO_SCQ,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A4ANIOS_OTRO_MCHAT,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A4ANIOS_OTRO_VABS,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A4ANIOS_OTRO_GMFCS,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A4ANIOS_OTRO_OBSERV,
			$evaluacion_neurodesarrollo->NEURODESAROLLO_2ANIOS_MOTORA,
			$evaluacion_neurodesarrollo->NEURODESAROLLO_2ANIOS_MOTORA_NIVEL,
			$evaluacion_neurodesarrollo->NEURODESAROLLO_2ANIOS_PARALISIS,
			$evaluacion_neurodesarrollo->NEURODESAROLLO_2ANIOS_PARALISIS_CUAL	,
			$evaluacion_neurodesarrollo->NEURODESAROLLO_2ANIOS_OTROS_TRANSTORNOS,
			$evaluacion_neurodesarrollo->NEURODESAROLLO_2ANIOS_OTROS_LENGUAJE	,
			$evaluacion_neurodesarrollo->NEURODESAROLLO_2ANIOS_OTROS_APRENDIZAJE
		);

		$retorno=$sentencia->execute(); 	
		$this->conexionDao->Cerrar();
		return $retorno;
	}
	

	public function actualizar($evaluacion_neurodesarrollo)
	{
	  $query = "UPDATE evaluacion_neurodesarrollo SET  
				`HIC_40_SEMANA`	=	 ? ,
				`ID_HIC_40_GRADO`	=	 ? ,
				`LPV_40SEMANAS` 	=	 ? ,
				`ROP_40_SEMANAS`	=	 ? ,
				`ROP_40_SEMANAS_GRADO`	=	 ? ,
				`BERA_40SEMANAS`	=	 ? ,
				`NEUROLOGICA_2_VISION`	=	 ? ,
				`NEUROLOGICA_2_VISION_CEGUERA` 	=	 ? ,
				`NEUROLOGICA_2_VISION_ESTRABISMO` 	=	 ? ,
				`NEUROLOGICA_2_VISION_REFRACCION` 	=	 ? ,
				`NEUROLOGICA_2_AUDICION` 	=	 ? ,
				`NEUROLOGICA_2_AUDICION_NO` 	=	 ? ,
				`NEUROLOGICA_2_MOTORA` 	=	 ? , 
				`NEUROLOGICA_2_PARALISIS` 	=	 ? ,
				`NEUROLOGICA_2_PARALISIS_SI` 	=	 ? ,
				`NEUROLOGICA_2_COGNITIVA` 	=	 ? ,
				`NEUROLOGICA_2_OTROS` 	=	 ? ,
				`NEUROLOGICA_2_OTROS_CONVULSIVO` 	=	 ? ,
				`NEUROLOGICA_2_OTROS_HIDROCEFALIA` 	=	 ? ,
				`PSICOMOTOR_2_EXAMEN` 	=	 ? ,
				`PSICOMOTOR_2_EX_HIPO` 	=	 ? ,
				`PSICOMOTOR_2_EX_HIPER` 	=	 ? ,
				`PSICOMOTOR_2_EX_FOCA` 	=	 ? ,
				`PSICOMOTOR_2_EXA_HEMI` 	=	 ? ,
				`PSICOMOTOR_2_AUDITIVA_SEN` 	=	 ? ,
				`PSICOMOTOR_2_AUDITIVA_SEN_HIPO` 	=	 ? ,
				`PSICOMOTOR_2_AUDITIVA_SEN_VISUAL` 	=	 ? ,
				`PSICOMOTOR_2_AUDITIVA_SEN_CIRUGIA` 	=	 ? ,
				`PSICOMOTOR_2_AUDITIVA_SEN_CIRUGIA_DESCI` 	=	 ? ,
				`PSICOMOTOR_2_AUDITIVA_RETRA_LENGUA` 	=	 ? ,
				`PSICOMOTOR_2_AUDITIVA_RETRA_LENGUA_SI` 	=	 ? ,
				`PSICOMOTOR_2_AUDITIVA_OTRO_CEFALIA` 	=	 ? ,
				`PSICOMOTOR_2_AUDITIVA_OTRO_SINDRO` 	=	 ? ,
				`PSICOMOTOR_2_AUDITIVA_OTRO_ALTERA` 	=	 ? ,
				`PSICOMOTOR_2_AUDITIVA_NEURO` 	=	 ? ,
				`PSICOMOTOR_A2ANIOS_MESES` 	=	 ? ,
				`PSICOMOTOR_A2ANIOS_EEDP_CUAL` 	=	 ? ,
				`PSICOMOTOR_A2ANIOS_EEDP_FECHA` 	=	 ? ,
				`PSICOMOTOR_A2ANIOS_EEDP_ANIOS` 	=	 ? ,
				`PSICOMOTOR_A2ANIOS_EEDP_MESES` 	=	 ? ,
				`PSICOMOTOR_A2ANIOS_EEDP_PUNTAJE` 	=	 ? ,
				`PSICOMOTOR_A2ANIOS_EEDP_NORMAL` 	=	 ? ,
				`PSICOMOTOR_A2ANIOS_EEDP_OBSERVACION` 	=	 ? ,
				`PSICOMOTOR_A2ANIOS_EAIS_CUAL` 	=	 ? ,
				`PSICOMOTOR_A2ANIOS_EAIS_FECHA` 	=	 ? ,
				`PSICOMOTOR_A2ANIOS_EAIS_ANIOS` 	=	 ? ,
				`PSICOMOTOR_A2ANIOS_EAIS_MESES` 	=	 ? ,
				`PSICOMOTOR_A2ANIOS_EAIS_PUNTAJE` 	=	 ? ,
				`PSICOMOTOR_A2ANIOS_EAIS_NORMAL` 	=	 ? ,
				`PSICOMOTOR_A2ANIOS_EAIS_OBSERVACION` 	=	 ? ,
				`PSICOMOTOR_A2ANIOS_CAT_CUAL` 	=	 ? ,
				`PSICOMOTOR_A2ANIOS_CAT_FECHA` 	=	 ? ,
				`PSICOMOTOR_A2ANIOS_CAT_ANIOS` 	=	 ? ,
				`PSICOMOTOR_A2ANIOS_CAT_MESES` 	=	 ? ,
				`PSICOMOTOR_A2ANIOS_CAT_PUNTAJE` 	=	 ? ,
				`PSICOMOTOR_A2ANIOS_CAT_NORMAL` 	=	 ? ,
				`PSICOMOTOR_A2ANIOS_CAT_OBSERVACION` 	=	 ? ,
				`PSICOMOTOR_A2ANIOS_ASQ_CUAL` 	=	 ? ,
				`PSICOMOTOR_A2ANIOS_ASQ_FECHA` 	=	 ? ,
				`PSICOMOTOR_A2ANIOS_ASQ_ANIOS` 	=	 ? ,
				`PSICOMOTOR_A2ANIOS_ASQ_MESES` 	=	 ? ,
				`PSICOMOTOR_A2ANIOS_ASQ_PUNTAJE` 	=	 ? ,
				`PSICOMOTOR_A2ANIOS_ASQ_NORMAL` 	=	 ? ,
				`PSICOMOTOR_A2ANIOS_ASQ_OBSERVACION` 	=	 ? ,
				`PSICOMOTOR_2A7ANIOS_TEPSI` 	=	 ? ,
				`PSICOMOTOR_2A7ANIOS_TEP_NORMAL` 	=	 ? ,
				`PSICOMOTOR_2A7ANIOS_TEP_FECHA` 	=	 ? ,
				`PSICOMOTOR_2A7ANIOS_TEP_ANIOS` 	=	 ? ,
				`PSICOMOTOR_2A7ANIOS_TEP_MESES` 	=	 ? ,
				`PSICOMOTOR_2A7ANIOS_TEP_PUNTAJE` 	=	 ? ,
				`PSICOMOTOR_2A7ANIOS_BAYLE` 	=	 ? ,
				`PSICOMOTOR_2A7ANIOS_BAYLE_VERSION` 	=	 ? ,
				`PSICOMOTOR_2A7ANIOS_BAYLE_VER_FECHA` 	=	 ? ,
				`PSICOMOTOR_2A7ANIOS_BAYLE_VER_ANIOS` 	=	 ? ,
				`PSICOMOTOR_2A7ANIOS_BAYLE_VER_MESES` 	=	 ? ,
				`PSICOMOTOR_2A7ANIOS_BAYLE_VER_MENTAL` 	=	 ? ,
				`PSICOMOTOR_2A7ANIOS_BAYLE_VER_MOTARA` 	=	 ? ,
				`PSICOMOTOR_2A7ANIOS_BAYLE_VER_CONDUCTA` 	=	 ? ,
				`PSICOMOTOR_2A7ANIOS_BAYLE_VER_NORMAL` 	=	 ? ,
				`PSICOMOTOR_2A7ANIOS_BAYLE_VER_FECHA_3` 	=	 ? ,
				`PSICOMOTOR_2A7ANIOS_BAYLE_VER_ANIOS_3` 	=	 ? ,
				`PSICOMOTOR_2A7ANIOS_BAYLE_VER_MESES_3` 	=	 ? ,
				`PSICOMOTOR_2A7ANIOS_BAYLE_VER_MOTARA_3` 	=	 ? ,
				`PSICOMOTOR_2A7ANIOS_BAYLE_VER_COGNI_3` 	=	 ? ,
				`PSICOMOTOR_2A7ANIOS_BAYLE_VER_LENG_3` 	=	 ? ,
				`PSICOMOTOR_2A7ANIOS_BAYLE_VER_SOCIO_3` 	=	 ? ,
				`PSICOMOTOR_2A7ANIOS_BAYLE_VER_COMPOR_3` 	=	 ? ,
				`PSICOMOTOR_2A7ANIOS_BAYLE_VER_NORMAL_3` 	=	 ? ,
				`PSICOMOTOR_A3ANIOS_RET_LENG` 	=	 ? ,
				`PSICOMOTOR_A3ANIOS_RET_LENG_TIPO` 	=	 ? ,
				`PSICOMOTOR_A3ANIOS_RET_LENG_REHAB` 	=	 ? ,
				`PSICOMOTOR_3ANIOS_RET_EXPRESIVO` 	=	 ? ,
				`PSICOMOTOR_3ANIOS_RET_EXPRESIVO_REHAB` 	=	 ? ,
				`PSICOMOTOR_2A4ANIOS_COEFICIENTE` 	=	 ? ,
				`PSICOMOTOR_2A4ANIOS_COE_FECHA_1` 	=	 ? ,
				`PSICOMOTOR_2A4ANIOS_COE_ANIOS_1` 	=	 ? ,
				`PSICOMOTOR_2A4ANIOS_COE_MESES_1` 	=	 ? ,
				`PSICOMOTOR_2A4ANIOS_COE_VERB_1` 	=	 ? ,
				`PSICOMOTOR_2A4ANIOS_COE_MANIPU_1` 	=	 ? ,
				`PSICOMOTOR_2A4ANIOS_COE_TOTAL_1` 	=	 ? ,
				`PSICOMOTOR_2A4ANIOS_COE_FECHA_2` 	=	 ? ,
				`PSICOMOTOR_2A4ANIOS_COE_ANIOS_2` 	=	 ? ,
				`PSICOMOTOR_2A4ANIOS_COE_MESES_2` 	=	 ? ,
				`PSICOMOTOR_2A4ANIOS_COE_VERB_2` 	=	 ? ,
				`PSICOMOTOR_2A4ANIOS_COE_MANIPU_2` 	=	 ? ,
				`PSICOMOTOR_2A4ANIOS_COE_PROCESA_2` 	=	 ? ,
				`PSICOMOTOR_2A4ANIOS_COE_LENGUAJE_2` 	=	 ? ,
				`PSICOMOTOR_2A4ANIOS_OTRO_MSCA` 	=	 ? ,
				`PSICOMOTOR_2A4ANIOS_OTRO_SCQ` 	=	 ? ,
				`PSICOMOTOR_2A4ANIOS_OTRO_MCHAT` 	=	 ? ,
				`PSICOMOTOR_2A4ANIOS_OTRO_VABS` 	=	 ? ,
				`PSICOMOTOR_2A4ANIOS_OTRO_GMFCS` 	=	 ? ,
				`PSICOMOTOR_2A4ANIOS_OTRO_OBSERV` 	=	 ? ,
				`NEURODESAROLLO_2ANIOS_MOTORA` 	=	 ? ,
				`NEURODESAROLLO_2ANIOS_MOTORA_NIVEL` 	=	 ? ,
				`NEURODESAROLLO_2ANIOS_PARALISIS` 	=	 ? ,
				`NEURODESAROLLO_2ANIOS_PARALISIS_CUAL` 	=	 ? ,
				`NEURODESAROLLO_2ANIOS_OTROS_TRANSTORNOS` 	=	 ? ,
				`NEURODESAROLLO_2ANIOS_OTROS_LENGUAJE` 	=	 ? ,
				`NEURODESAROLLO_2ANIOS_OTROS_APRENDIZAJE`	=	 ? 
				where  `ID_CONTROL`  = ? ;";
				//die;
		$this->conexionDao->Abrir();
		$sentencia = $this->conexionDao->prepare($query);		
		$sentencia->bind_param("sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss",
			$evaluacion_neurodesarrollo->HIC_40_SEMANA,
			$evaluacion_neurodesarrollo->ID_HIC_40_GRADO,
			$evaluacion_neurodesarrollo->LPV_40SEMANAS,
			$evaluacion_neurodesarrollo->ROP_40_SEMANAS,
			$evaluacion_neurodesarrollo->ROP_40_SEMANAS_GRADO,
			$evaluacion_neurodesarrollo->BERA_40SEMANAS,
			$evaluacion_neurodesarrollo->NEUROLOGICA_2_VISION,
			$evaluacion_neurodesarrollo->NEUROLOGICA_2_VISION_CEGUERA,
			$evaluacion_neurodesarrollo->NEUROLOGICA_2_VISION_ESTRABISMO,
			$evaluacion_neurodesarrollo->NEUROLOGICA_2_VISION_REFRACCION,
			$evaluacion_neurodesarrollo->NEUROLOGICA_2_AUDICION,
			$evaluacion_neurodesarrollo->NEUROLOGICA_2_AUDICION_NO	,
			$evaluacion_neurodesarrollo->NEUROLOGICA_2_MOTORA,
			$evaluacion_neurodesarrollo->NEUROLOGICA_2_PARALISIS	,
			$evaluacion_neurodesarrollo->NEUROLOGICA_2_PARALISIS_SI	,
			$evaluacion_neurodesarrollo->NEUROLOGICA_2_COGNITIVA	,
			$evaluacion_neurodesarrollo->NEUROLOGICA_2_OTROS,
			$evaluacion_neurodesarrollo->NEUROLOGICA_2_OTROS_CONVULSIVO,
			$evaluacion_neurodesarrollo->NEUROLOGICA_2_OTROS_HIDROCEFALIA,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2_EXAMEN,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2_EX_HIPO,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2_EX_HIPER,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2_EX_FOCA,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2_EXA_HEMI,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2_AUDITIVA_SEN	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2_AUDITIVA_SEN_HIPO,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2_AUDITIVA_SEN_VISUAL,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2_AUDITIVA_SEN_CIRUGIA,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2_AUDITIVA_SEN_CIRUGIA_DESCI,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2_AUDITIVA_RETRA_LENGUA,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2_AUDITIVA_RETRA_LENGUA_SI	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2_AUDITIVA_OTRO_CEFALIA,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2_AUDITIVA_OTRO_SINDRO,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2_AUDITIVA_OTRO_ALTERA,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2_AUDITIVA_NEURO,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_MESES	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_EEDP_CUAL,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_EEDP_FECHA,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_EEDP_ANIOS,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_EEDP_MESES,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_EEDP_PUNTAJE,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_EEDP_NORMAL,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_EEDP_OBSERVACION	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_EAIS_CUAL,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_EAIS_FECHA,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_EAIS_ANIOS,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_EAIS_MESES,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_EAIS_PUNTAJE,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_EAIS_NORMAL,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_EAIS_OBSERVACION	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_CAT_CUAL,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_CAT_FECHA,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_CAT_ANIOS,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_CAT_MESES,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_CAT_PUNTAJE,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_CAT_NORMAL,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_CAT_OBSERVACION,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_ASQ_CUAL,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_ASQ_FECHA,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_ASQ_ANIOS,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_ASQ_MESES,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_ASQ_PUNTAJE,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_ASQ_NORMAL,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A2ANIOS_ASQ_OBSERVACION,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_TEPSI	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_TEP_NORMAL,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_TEP_FECHA,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_TEP_ANIOS,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_TEP_MESES,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_TEP_PUNTAJE,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_BAYLE	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_BAYLE_VERSION,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_BAYLE_VER_FECHA	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_BAYLE_VER_ANIOS	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_BAYLE_VER_MESES	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_BAYLE_VER_MENTAL	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_BAYLE_VER_MOTARA	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_BAYLE_VER_CONDUCTA	,			
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_BAYLE_VER_NORMAL	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_BAYLE_VER_FECHA_3	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_BAYLE_VER_ANIOS_3	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_BAYLE_VER_MESES_3	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_BAYLE_VER_MOTARA_3	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_BAYLE_VER_COGNI_3	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_BAYLE_VER_LENG_3	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_BAYLE_VER_SOCIO_3	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_BAYLE_VER_COMPOR_3	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A7ANIOS_BAYLE_VER_NORMAL_3	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A3ANIOS_RET_LENG,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A3ANIOS_RET_LENG_TIPO,
			$evaluacion_neurodesarrollo->PSICOMOTOR_A3ANIOS_RET_LENG_REHAB,
			$evaluacion_neurodesarrollo->PSICOMOTOR_3ANIOS_RET_EXPRESIVO,
			$evaluacion_neurodesarrollo->PSICOMOTOR_3ANIOS_RET_EXPRESIVO_REHAB	,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A4ANIOS_COEFICIENTE,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A4ANIOS_COE_FECHA_1,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A4ANIOS_COE_ANIOS_1,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A4ANIOS_COE_MESES_1,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A4ANIOS_COE_VERB_1,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A4ANIOS_COE_MANIPU_1,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A4ANIOS_COE_TOTAL_1,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A4ANIOS_COE_FECHA_2,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A4ANIOS_COE_ANIOS_2,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A4ANIOS_COE_MESES_2,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A4ANIOS_COE_VERB_2,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A4ANIOS_COE_MANIPU_2,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A4ANIOS_COE_PROCESA_2,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A4ANIOS_COE_LENGUAJE_2,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A4ANIOS_OTRO_MSCA,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A4ANIOS_OTRO_SCQ,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A4ANIOS_OTRO_MCHAT,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A4ANIOS_OTRO_VABS,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A4ANIOS_OTRO_GMFCS,
			$evaluacion_neurodesarrollo->PSICOMOTOR_2A4ANIOS_OTRO_OBSERV,
			$evaluacion_neurodesarrollo->NEURODESAROLLO_2ANIOS_MOTORA,
			$evaluacion_neurodesarrollo->NEURODESAROLLO_2ANIOS_MOTORA_NIVEL,
			$evaluacion_neurodesarrollo->NEURODESAROLLO_2ANIOS_PARALISIS,
			$evaluacion_neurodesarrollo->NEURODESAROLLO_2ANIOS_PARALISIS_CUAL	,
			$evaluacion_neurodesarrollo->NEURODESAROLLO_2ANIOS_OTROS_TRANSTORNOS,
			$evaluacion_neurodesarrollo->NEURODESAROLLO_2ANIOS_OTROS_LENGUAJE	,
			$evaluacion_neurodesarrollo->NEURODESAROLLO_2ANIOS_OTROS_APRENDIZAJE,
			$evaluacion_neurodesarrollo->ID_CONTROL
		);

		$retorno=$sentencia->execute(); 	
		$this->conexionDao->Cerrar();
		return $retorno;

		
	}
	
	
	public function buscarId($id)
	{
		$query = "SELECT * FROM evaluacion_neurodesarrollo WHERE `ID_CONTROL`= ? ";

		$this->conexionDao->Abrir();
		
		$sentencia = $this->conexionDao->prepare($query);
		$sentencia->bind_param("i", $id );		
		$sentencia->execute();
		$resultado = $sentencia->get_result();
		$row = $resultado->fetch_assoc();
		

		$this->conexionDao->Cerrar();
		return $row;
	}
	
		
	
	
}